baseurl: ''
title: perhenrik
subtitle: Content-centric blogging
author: Per Henrik Johansen
simple_search: http://google.com/search
description: Developer
name: perhenrik
markdown: kramdown
highlighter: rouge
permalink: /articles/:short_year/:title
timezone: Europe/Oslo
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
